//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baybakov_Glazki
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Agent
    {
        public Agent()
        {
            this.AgentPriorityHistory = new HashSet<AgentPriorityHistory>();
            this.ProductSale = new HashSet<ProductSale>();
            this.Shop = new HashSet<Shop>();
        }
    
        public int ID { get; set; }
        public int AgentTypeID { get; set; }
        public string AgentCharacterTypeID
        {
            get
            {
                var Ch = BaybakovGlazkiSaveEntities.GetContext().AgentType.Where(p => p.ID == AgentTypeID);

                return Ch.ToList().First().Title;
            }
            set
            {

            }
        }
        public string Title { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Logo { get; set; }
        public string Address { get; set; }
        public int Priority { get; set; }
        public string DirectorName { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public decimal Sales {
            get
            {
                decimal agentSales = 0;

                var sales = BaybakovGlazkiSaveEntities.GetContext().ProductSale.Where(p => p.AgentID == ID);

                foreach (ProductSale sale in sales)
                {
                    agentSales += sale.Cost;
                }

                return agentSales;
            }

            set
            {
                
            } 
        }
        public int Discount
        {
            get
            {
                int discount = 0;

                if (Sales >= 0 && Sales < 10000) discount = 0;
                if (Sales >= 10000 && Sales < 50000) discount = 5;
                if (Sales >= 50000 && Sales < 150000) discount = 10;
                if (Sales >= 150000 && Sales < 500000) discount = 20;
                if (Sales >= 500000) discount = 25;

                return discount;
            }
        }

        public virtual AgentType AgentType { get; set; }
        public virtual ICollection<AgentPriorityHistory> AgentPriorityHistory { get; set; }
        public virtual ICollection<ProductSale> ProductSale { get; set; }
        public virtual ICollection<Shop> Shop { get; set; }
    }
}
