//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baybakov_Glazki
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ProductSale
    {
        public int ID { get; set; }
        public int AgentID { get; set; }
        public int ProductID { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int ProductCount { get; set; }
        public decimal Cost {
            get
            {
                decimal all = 0;
                var Sale = BaybakovGlazkiSaveEntities.GetContext().Product.Where(p => p.ID == ProductID);

                foreach (Product item in Sale) {
                    all += item.MinCostForAgent * ProductCount;
                }

                return all;
            }
            set
            {

            } 
        }
    
        public virtual Agent Agent { get; set; }
        public virtual Product Product { get; set; }
    }
}
